"""Record installed bytes and source identity without retaining local paths or credentials."""

import hashlib
import importlib.metadata
import json
import subprocess
from pathlib import Path
from urllib.parse import unquote, urlsplit


def package_provenance(name):
    distribution = importlib.metadata.distribution(name)
    files = {}
    for entry in distribution.files or []:
        # Ignore generated bytecode and machine-specific .pth/installer records.
        if entry.suffix == ".py" and ".dist-info" not in str(entry):
            path = Path(distribution.locate_file(entry))
            if path.is_file():
                files[str(entry)] = hashlib.sha256(path.read_bytes()).hexdigest()
    result = {
        "version": distribution.version,
        "installed_python_files": len(files),
        "installed_python_sha256": hashlib.sha256(
            json.dumps(files, sort_keys=True).encode()
        ).hexdigest()
        if files
        else None,
        "wheel_record_sha256": hashlib.sha256(
            (distribution.read_text("RECORD") or "").encode()
        ).hexdigest(),
    }
    direct = json.loads(distribution.read_text("direct_url.json") or "{}")
    vcs = direct.get("vcs_info", {})
    if vcs.get("commit_id"):
        result["source_commit"] = vcs["commit_id"]
    url = urlsplit(direct.get("url", ""))
    if url.scheme == "file":
        source = Path(unquote(url.path))
        try:
            commit = subprocess.check_output(
                ["git", "-C", str(source), "rev-parse", "HEAD"],
                text=True,
                stderr=subprocess.DEVNULL,
                timeout=5,
            ).strip()
            dirty = subprocess.check_output(
                ["git", "-C", str(source), "status", "--porcelain", "--", "."],
                text=True,
                stderr=subprocess.DEVNULL,
                timeout=5,
            ).strip()
        except (OSError, subprocess.SubprocessError):
            result["local_source_available"] = False
        else:
            result["source_commit"] = commit
            result["source_dirty"] = bool(dirty)
            comparable = {key: digest for key, digest in files.items() if (source / key).is_file()}
            result["installed_files_match_source"] = (
                all(
                    hashlib.sha256((source / key).read_bytes()).hexdigest() == digest
                    for key, digest in comparable.items()
                )
                if comparable
                else None
            )
            result["compared_source_files"] = len(comparable)
    return result
